/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scottlogic.datahelix.generator;

import org.junit.Test;
import static org.junit.Assert.*;

public class DataHelixRunnerMainTest {
    @Test public void testAppHasAGreeting() {
        DataHelixRunnerMain classUnderTest = new DataHelixRunnerMain();
      //  assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
